### PR TITLE
React JSX PPX: generalize calling expressions to all identifiers

### PR DESCRIPTION
**Pull request by anmonteiro**
- After https://github.com/reasonml/reason/pull/2541, Longidents are now being properly passed
- The React JSX PPX was relying on the previous, odd behavior, which appended `createElement` at the end of a long identifier.

This change relaxes the constraint that JSX calls need to end with `make` or `createElement`. The following case was affected:

```reason
module Internal = {
  [@react.component]
  let header = () => <div />;
};

[@react.component]
let make = () => <Internal.header />;
```

### Test plan

- Included a test case that failed to compile before this change.

### CODE REVIEW

**Comment by Mathspy** [comment]
Wait so we're no longer forced to use `make`s for React components?

**Comment by anmonteiro** [comment]
Nope, the example above should work, and works for upstream as well.

**Comment by Mathspy** [comment]
Aha I see

**Comment by anmonteiro** [comment]
Another relatively safe change, backed by a test too. Gonna go ahead an merge.

**Pull request merged**
